{
    'name': 'Hospital Management',
    'Version': '1.0.0',
    'sequence': -100,
    'author': 'Simon Mburu',
    'website': 'https://mburunjoroge.netlify.app/',
    'category': 'Health',
    'summary': 'Hospital management system',
    'description': 'Hospital management system',
    'depends': [],
    'data': [
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/patient.xml',
    ],
    'installable': True,
    'auto-install': False,
    'application': True,
    'license': 'LGPL-3',
}